KijijitoForever/KijijitoForever/Controllers/RatingsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using KijijitoForever.Models;

namespace KijijitoForever.Controllers
{
    public class RatingsController : Controller
    {
        private readonly kijijito_identityContext _context;

        public RatingsController(kijijito_identityContext context)
        {
            _context = context;
        }

        // GET: Ratings
        public async Task<IActionResult> Index()
        {
            return View(await _context.Ratings.ToListAsync());
        }

        // GET: Ratings/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ratings = await _context.Ratings
                .FirstOrDefaultAsync(m => m.Id == id);
            if (ratings == null)
            {
                return NotFound();
            }

            return View(ratings);
        }

        // GET: Ratings/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Ratings/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,UserId,RatedUserId,Rating,Comment,CreationTs")] Ratings ratings)
        {
            if (ModelState.IsValid)
            {
                _context.Add(ratings);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(ratings);
        }

        // GET: Ratings/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ratings = await _context.Ratings.FindAsync(id);
            if (ratings == null)
            {
                return NotFound();
            }
            return View(ratings);
        }

        // POST: Ratings/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,UserId,RatedUserId,Rating,Comment,CreationTs")] Ratings ratings)
        {
            if (id != ratings.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(ratings);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RatingsExists(ratings.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(ratings);
        }

        // GET: Ratings/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ratings = await _context.Ratings
                .FirstOrDefaultAsync(m => m.Id == id);
            if (ratings == null)
            {
                return NotFound();
            }

            return View(ratings);
        }

        // POST: Ratings/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var ratings = await _context.Ratings.FindAsync(id);
            _context.Ratings.Remove(ratings);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool RatingsExists(int id)
        {
            return _context.Ratings.Any(e => e.Id == id);
        }
    }
}

KijijitoForever/KijijitoForever/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - KijijitoForever Admin View</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/mainstyle.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="~/images/1200px-Kijijito_Logo.png" class="logo-img-header" />
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="AspNetUsers" asp-action="Index">List of Users</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Products" asp-action="Index">List of Products</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Conversations" asp-action="Index">List of Conversations</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Ratings" asp-action="Index">List of Ratings</a>
                        </li>
                        <li class="nav-item">
                            @if (User.Identity.IsAuthenticated)
                            {
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Logout">@User.Identity.Name, Logout</a>
                            }
                            else
                            {
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">Login</a>
                            }
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - KijijitoForever - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

KijijitoForever/KijijitoForever/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - KijijitoForever</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/mainstyle.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="~/images/1200px-Kijijito_Logo.png" class="logo-img-header" />
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        @*<li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>*@
                        <li class="nav-item mt-3">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        @*<li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="AspNetUsers" asp-action="Index">List of Users</a>
                        </li>*@
                        <li class="nav-item mt-3">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Products" asp-action="Index">See all Products</a>
                        </li>
                        @*<li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Conversations" asp-action="Index">List of Conversations</a>
                        </li>*@
                        @*<li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Ratings" asp-action="Index">List of Ratings</a>
                        </li>*@
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item user-info-li mt-3">
                                <p style="padding: 0.5rem;">Hello </p>
                            </li>
                            <li class="nav-item mt-3">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Details" asp-route-username="@User.Identity.Name" >@User.Identity.Name</a>
                            </li>
                            <li class="nav-item mt-3">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Logout"> Logout</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item user-info-li mt-3">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">Login</a>
                            </li>
                            <li class="nav-item pl-5 mt-3">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Create">Register</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="main-body-div">
        <div class="container">
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>
    </div>
    

    <footer class="border-top footer text-muted container-footer mt-5 pt-3">
        <div class="container ">
            <div class="row">
                <div class="col-12">
                    <div class="row">
                        <div class="col-9">
                            <h6 class="pt-2">SHOP BY CATEGORIES</h6>
                        </div>
                        <div class="col-3">
                            <h6 class="pt-2">LOGIN</h6>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-3">
                            <div class="row m-0 p-0"><a class="m-0 p-0" asp-area="" asp-controller="Products" asp-action="Index">All Products</a></div>
                            <div class="row m-0 p-0"><a class="m-0 p-0" asp-area="" asp-controller="Products" asp-action="Index" asp-route-category="Cars">Cars</a></div>
                            <div class="row m-0 p-0"><a class="m-0 p-0" asp-area="" asp-controller="Products" asp-action="Index" asp-route-category="Clothing">Clothing</a></div>
                        </div>
                        <div class="col-3">
                            <div class="row m-0 p-0"><a class="m-0 p-0" asp-area="" asp-controller="Products" asp-action="Index" asp-route-category="Electronics">Electronics</a></div>
                            <div class="row m-0 p-0"><a class="m-0 p-0" asp-area="" asp-controller="Products" asp-action="Index" asp-route-category="Entertainment">Entertainment</a></div>
                            <div class="row m-0 p-0"><a class="m-0 p-0" asp-area="" asp-controller="Products" asp-action="Index" asp-route-category="Appliances">Appliances</a></div>
                        </div>
                        <div class="col-3">
                            <div class="row m-0 p-0"><a class="m-0 p-0" asp-area="" asp-controller="Products" asp-action="Index" asp-route-category="ToysAndGames">Toys and Games</a></div>
                            <div class="row m-0 p-0"><a class="m-0 p-0" asp-area="" asp-controller="Products" asp-action="Index" asp-route-category="Other">Other</a></div>
                            <div class="row m-0 p-0"><a class="m-0 p-0" asp-area="" asp-controller="Products" asp-action="Create" >Sell your Product</a></div>
                        </div>
                        <div class="col-3">
                            <div class="row m-0 p-0"><a class="m-0 p-0" asp-area="" asp-controller="Account" asp-action="Login">Login</a></div>
                            <div class="row m-0 p-0"><a class="m-0 p-0" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a></div>
                        </div>
                    </div>
                </div>
                <div class="col-12 mt-3">

                    <p class="text-center"><a asp-controller="Home" asp-action="Index"><img src="~/images/1200px-Kijijito_Logo.png" class="logo-img-header" /></a> &copy; 2020 - Kijijito - The little Kijiji clone | Made by : <a href="https://www.linkedin.com/in/giovanademoraesourique/">Giovana de Moraes Ourique</a> &amp; <a href="https://www.linkedin.com/in/saulocarranza/">Saulo Carranza</a></p>
                </div>
            </div>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>