KijijitoForever/KijijitoForever/Models/Products.cs
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace KijijitoForever.Models
{
    public partial class Products
    {
        public int Id { get; set; }

        [Required]
        public int UserId { get; set; }

        [Required]
        [StringLength(50, MinimumLength = 5, ErrorMessage = "{0} should be between 5 to 50 characters")]
        public string Title { get; set; }

        [Required]
        [StringLength(1000, MinimumLength = 10, ErrorMessage = "{0} should be between 10 to 1000 characters")]
        public string Description { get; set; }

        [Range(0, 49999.99)]
        public decimal Price { get; set; }

        [NotMapped]
        [DisplayName("Upload Picture 1")]
        [UploadValidationAttribute]
        public IFormFile ImageFile1 { get; set; }

        [NotMapped]
        [DisplayName("Upload Picture 2")]
        [UploadValidationAttribute]
        public IFormFile ImageFile2 { get; set; }

        [NotMapped]
        [DisplayName("Upload Picture 3")]
        [UploadValidationAttribute]
        public IFormFile ImageFile3 { get; set; }

        public string Image1 { get; set; }
        public string Image2 { get; set; }
        public string Image3 { get; set; }
        public ProductStatusEnum Status { get; set; }
        public DateTime PostedTs { get; set; }
        public ProductCategoryEnum? Category { get; set; }

        public virtual AspNetUsers User { get; set; }
    }

    public enum ProductStatusEnum : int
    {
        Available = 1,
        Sold = 2,
        Deleted = 3
    }

    public enum ProductCategoryEnum : int
    {
        Cars = 1,
        Clothing = 2,
        Electronics = 3,
        Entertainment = 4,
        [Display(Name = "Home & Appliances")]
        HomeAppliances = 5,
        [Display(Name = "Toys & Games")]
        ToysAndGames = 6,
        Other = 7
    }



}

KijijitoForever/KijijitoForever/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;

namespace KijijitoForever.Models
{
    public class ProductsController : Controller
    {
        private readonly kijijito_identityContext _context;
        private readonly IWebHostEnvironment _webHostEnvironment;
        private readonly UserService _userService;

        public ProductsController(kijijito_identityContext context, IWebHostEnvironment webHostEnvironment)
        {
            _context = context;
            _webHostEnvironment = webHostEnvironment;
            _userService = new UserService(_context);
        }

        // GET: Products
        public async Task<IActionResult> Index(ProductCategoryEnum? Category = null, string SearchString = "", string CurrentFilter = "", int? UserId = null, int? pageNumber = null)
        {
            ViewData["CurrentCategory"] = Category;
            if (!String.IsNullOrEmpty(SearchString))
            {
                pageNumber = 1;
            }
            else
            {
                SearchString = CurrentFilter;
            }
            ViewData["CurrentFilter"] = SearchString;
            var products = from p in _context.Products.Where(p => p.Status != ProductStatusEnum.Deleted).OrderByDescending(p => p.Id).Include(p => p.User) select p;
            if (Category != null)
            {
                products = products.Where(p => p.Category == Category);
            }
            ViewData["CurrentUserId"] = UserId;
            if (UserId != null) {
                products = products.Where(p => p.UserId == UserId);
            }
            if (!String.IsNullOrEmpty(SearchString))
            {
                products = products.Where(s => s.Title.ToUpper().Contains(SearchString.ToUpper())
                                       || s.Description.ToUpper().Contains(SearchString.ToUpper()));
            }
            int pageSize = 3;
            return View(await PaginatedList<Products>.CreateAsync(products.AsNoTracking(), pageNumber ?? 1, pageSize));
        }

        // GET: Products/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            if (User.Identity.Name != null)
            {
                var currUserId = await _userService.GetCurrentUserId(User.Identity.Name);
                ViewBag.CurrentId = currUserId;
            }
            else
            {
                ViewBag.CurrentId = 0;
            }
            var products = await _context.Products
                .Include(p => p.User)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (products == null)
            {
                return NotFound();
            }

            return View(products);
        }

        // GET: Products/Create
        [Authorize]
        public IActionResult Create()
        {
            //ViewData["UserId"] = new SelectList(_context.AspNetUsers, "Id", "Id");
            return View();
        }

        // POST: Products/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Create([Bind("Id,UserId,Title,Description,Price,ImageFile1,ImageFile2,ImageFile3,Status,PostedTs,Category")] Products products)
        { 
            products.UserId = await _userService.GetCurrentUserId(User.Identity.Name);
            if (ModelState.IsValid)
            {
                string targetPath = _webHostEnvironment.WebRootPath + "/productImages";
                if (products.ImageFile1 != null)
                {
                    // in the product field from the Model Product put the name of the image file by combining the product id and the file extension   
                    string filename1 = GenerateFileName(targetPath, products.ImageFile1);
                    // assign new file name to Image1 field to save on database
                    products.Image1 = filename1;
                    // move image to folder
                    SaveImageToFolder(targetPath, filename1, products.ImageFile1);
                }
                if (products.ImageFile2 != null)
                {
                    string filename2 = GenerateFileName(targetPath, products.ImageFile2);
                    products.Image2 = filename2;
                    SaveImageToFolder(targetPath, filename2, products.ImageFile2);
                }
                else
                {
                    products.Image2 = products.Image1;
                }
                if (products.ImageFile3 != null)
                {
                    string filename3 = GenerateFileName(targetPath, products.ImageFile3);
                    products.Image3 = filename3;
                    SaveImageToFolder(targetPath, filename3, products.ImageFile3);
                }
                else
                {
                    products.Image3 = products.Image1;
                }

                _context.Add(products);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
           // ViewData["UserId"] = new SelectList(_context.AspNetUsers, "Id", "Email", products.UserId);
            return View(products);
        }

        // GET: Products/Edit/5
        [Authorize]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var products = await _context.Products.FindAsync(id);
            if (products == null)
            {
                return NotFound();
            }
            return View(products);
        }

        // POST: Products/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Edit(int id, [Bind("Id,UserId,Title,Description,Price,ImageFile1,ImageFile2,ImageFile3,Image1,Image2,Image3,Status,Category")] Products products) //[Bind("Id,UserId,Title,Description,Price,Image1,Image2,Image3,Status,PostedTs,Category")]
        { 
            if (id != products.Id)
            {
                return NotFound();
            }
            products.UserId = await _userService.GetCurrentUserId(User.Identity.Name);
            if (ModelState.IsValid)
            {
                try
                {
                string targetPath = _webHostEnvironment.WebRootPath + "/productImages";
                if (products.ImageFile1 != null)
                {
                    //in the product field from the Model Product put the name of the image file by combining the product id and the file extension   
                    string filename1 = GenerateFileName(targetPath, products.ImageFile1);
                    products.Image1 = filename1;
                    SaveImageToFolder(targetPath, filename1, products.ImageFile1);
                }
                else
                    {
                        products.Image1 = products.Image1;
                    }
                if (products.ImageFile2 != null)
                {
                    string filename2 = GenerateFileName(targetPath, products.ImageFile2);
                    products.Image2 = filename2;
                    SaveImageToFolder(targetPath, filename2, products.ImageFile2);
                }
                    else
                    {
                        products.Image2 = products.Image2;
                    }
                    if (products.ImageFile3 != null)
                {
                    string filename3 = GenerateFileName(targetPath, products.ImageFile3);
                    products.Image3 = filename3;
                    SaveImageToFolder(targetPath, filename3, products.ImageFile3);
                }
                    else
                    {
                        products.Image3 = products.Image3;
                    }


                    _context.Update(products);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProductsExists(products.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(products);
        }

        // GET: Products/Delete/5
        [Authorize]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var products = await _context.Products
                .Include(p => p.User)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (products == null)
            {
                return NotFound();
            }

            return View(products);
        }

        // POST: Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var products = await _context.Products.FindAsync(id);
            products.Status = ProductStatusEnum.Deleted;
            try

KijijitoForever/KijijitoForever/Views/Products/Create.cshtml
@model KijijitoForever.Models.Products

@{
    ViewData["Title"] = "Create";
}

<h1>Sell your product!</h1>

<h4>Products</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @*<div class="form-group">
                <label asp-for="UserId" class="control-label"></label>
                <select asp-for="UserId" class="form-control" asp-items="ViewBag.UserId"></select>
            </div>*@
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImageFile1" class="control-label"></label>
                <input asp-for="ImageFile1" accept="image/*" class="form-control" />
                <span asp-validation-for="ImageFile1" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImageFile2" class="control-label"></label>
                <input asp-for="ImageFile2" accept="image/*" class="form-control" />
                <span asp-validation-for="ImageFile2" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImageFile3" class="control-label"></label>
                <input asp-for="ImageFile3" accept="image/*" class="form-control" />
                <span asp-validation-for="ImageFile3" class="text-danger"></span>
            </div>
            @*<div class="form-group">
                <label asp-for="Image1" class="control-label"></label>
                <input asp-for="Image1" class="form-control" />
                <span asp-validation-for="Image1" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Image2" class="control-label"></label>
                <input asp-for="Image2" class="form-control" />
                <span asp-validation-for="Image2" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Image3" class="control-label"></label>
                <input asp-for="Image3" class="form-control" />
                <span asp-validation-for="Image3" class="text-danger"></span>
            </div>*@
        <div class="form-group">
            @*<label asp-for="Status" class="control-label"></label>*@
            <input asp-for="Status" class="form-control" hidden value="Available"/>
            <span asp-validation-for="Status" class="text-danger"></span>
        </div>
            <div class="form-group">
                <label asp-for="Category" class="control-label"></label>
                @*<input asp-for="Category" class="form-control" />*@
                <select asp-for="Category" asp-items="Html.GetEnumSelectList<ProductCategoryEnum>()" class="form-control">
                    <option selected="selected" value="">Please select</option>
                </select>
                <span asp-validation-for="Category" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to Products</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

KijijitoForever/KijijitoForever/Views/Products/Delete.cshtml
@model KijijitoForever.Models.Products

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Products</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Image1)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Image1)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Image2)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Image2)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Image3)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Image3)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Status)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PostedTs)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PostedTs)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Category)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Category)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.User)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.User.Id)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

KijijitoForever/KijijitoForever/Views/Products/Details.cshtml
@model KijijitoForever.Models.Products

@{
    ViewData["Title"] = "Details";
    var currentUserId = ViewBag.CurrentId;
}

<h1>Details</h1>

<div class="container">
    <div class="row">
        <div class="col-sm-8">
            <div class="row">
                <h2> @Html.DisplayFor(model => model.Title)</h2><br />
                <h2 style="color:green;"> $ @Html.DisplayFor(model => model.Price)</h2>
            </div>
            <div class="row">
                <div id="carouselExampleFade" class="carousel slide carousel-fade" data-ride="carousel">
                    <div class="carousel-inner">
                        <div class="carousel-item active">
                            <img class="img-fluid w-80" src="~/productImages/@Html.DisplayFor(model => model.Image1)" alt="First slide">
                        </div>
                        <div class="carousel-item">
                            <img class="img-fluid w-80" src="~/productImages/@Html.DisplayFor(model => model.Image2)" alt="Second slide">
                        </div>
                        <div class="carousel-item">
                            <img class="img-fluid w-80" src="~/productImages/@Html.DisplayFor(model => model.Image3)" alt="Third slide">
                        </div>
                    </div>
                    <a class="carousel-control-prev" href="#carouselExampleFade" role="button" data-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a class="carousel-control-next" href="#carouselExampleFade" role="button" data-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                    </a>
                </div>
            </div>
            <div class="row">
                <h5>@Html.DisplayNameFor(model => model.Description)</h5>
                <h5>@Html.DisplayFor(model => model.Description)</h5>
            </div>
        </div>

        <div class="col-sm-4">
            <div class="align-middle text-center" style="height: 60px;">
                <p>Posted on  @Html.DisplayFor(model => model.PostedTs)</p>
                <p>@Html.DisplayFor(model => model.Status)</p>
            </div>

            <div class="border text-center mb-2" style="background-color:whitesmoke;">
                <p>Contact @Html.DisplayFor(model => model.User.UserName) </p>
                <form asp-area="" asp-controller="ChatRoom" asp-action="Index" asp-route-id="@Model.User.Id">
                    <button class="btn" type="submit" style="background-color:blueviolet;">Start a conversation!</button>
                </form>
                @*<input class="form-control align-middle m-sm-1" placeholder="Your message" value="Hi, I'm interested.............." />
                    <input type="submit" value="Send a message" class="btn w-100 m-sm-1" style="background-color:blueviolet;" />*@
            </div>
            <div class="border text-center" style="background-color:whitesmoke;">
                <p>Seller information</p>
                <p>Email:  @Html.DisplayFor(model => model.User.Email)</p>
                <p>Phone:  @Html.DisplayFor(model => model.User.PhoneNumber)</p>
            </div>
        </div>
    </div>
</div>

<div>
    @if (currentUserId == Model.UserId)
    {
        <span>
            <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
            <a asp-action="Delete" asp-route-id="@Model.Id">Delete</a> |
        </span>
    }
    <a asp-action="Index">Back to Products</a>
</div>

KijijitoForever/KijijitoForever/Views/Products/Index.cshtml
@model PaginatedList<KijijitoForever.Models.Products>

@{
    ViewData["Title"] = "Index";
}

<div class="row my-4">
    <div class="col-md-6 text-center my-auto">
        <h5><a asp-action="Create">Sell your Product</a></h5>
    </div>
    <div class="col-md-4">
        <form asp-controller="Products" asp-action="Index" method="get">
            <div class="form-actions">
                <div class="input-group mb-3">
                    <input type="text" class="form-control" name="SearchString" value="@ViewData["CurrentFilter"]" />
                    <div class="input-group-append">
                        <input type="submit" value="Search" class="btn btn-secondary" />
                    </div>

                </div>
            </div>
        </form>
    </div>
    <div class="col-md-2 my-auto">
        <a asp-controller="Products" asp-action="Index" asp-route-category=@ViewData["CurrentCategory"]> | Clear Search</a>
    </div>
</div>

<div class="row">
    <div class="col-md-3">
        <h5>Filter by Category</h5>
        <div class="list-group" id="myList">
            <a class="btn list-group-item active" asp-area="" asp-controller="Products" asp-action="Index" asp-route-category=null asp-route-searchString="@ViewData["CurrentFilter"]">All Products</a>
            <a class="btn list-group-item" asp-area="" asp-controller="Products" asp-action="Index" asp-route-category="Cars" asp-route-searchString="@ViewData["CurrentFilter"]">Cars</a>
            <a class="btn list-group-item" asp-area="" asp-controller="Products" asp-action="Index" asp-route-category="Clothing" asp-route-searchString="@ViewData["CurrentFilter"]">Clothing</a>
            <a class="btn list-group-item" asp-area="" asp-controller="Products" asp-action="Index" asp-route-category="Electronics" asp-route-searchString="@ViewData["CurrentFilter"]">Electronics</a>
            <a class="btn list-group-item" asp-area="" asp-controller="Products" asp-action="Index" asp-route-category="Entertainment" asp-route-searchString="@ViewData["CurrentFilter"]">Entertainment</a>
            <a class="btn list-group-item" asp-area="" asp-controller="Products" asp-action="Index" asp-route-category="HomeAppliances" asp-route-searchString="@ViewData["CurrentFilter"]">Home Appliances</a>
            <a class="btn list-group-item" asp-area="" asp-controller="Products" asp-action="Index" asp-route-category="ToysAndGames" asp-route-searchString="@ViewData["CurrentFilter"]">Toys And Games</a>
            <a class="btn list-group-item" asp-area="" asp-controller="Products" asp-action="Index" asp-route-category="Other" asp-route-searchString="@ViewData["CurrentFilter"]">Other</a>
        </div>
    </div>

    <div class="col-md-9">
        @foreach (var item in Model)
        {
            <div class="row my-3">
                <div class="col-sm-4">
                    <img class="img-fluid w-80" src="~/productImages/@Html.DisplayFor(modelItem => item.Image1)"/>
                </div>
                <div class="col-sm-5">
                    <h3>@Html.DisplayFor(modelItem => item.Title)</h3>
                    <div class="description_wrap mb-2">
                        <p>@Html.DisplayFor(modelItem => item.Description)</p>
                    </div>               
                    <p>@Html.DisplayFor(modelItem => item.Category)</p>
                    <p>@Html.DisplayFor(modelItem => item.Status) -  @Html.DisplayFor(modelItem => item.PostedTs)</p>
                    @*<p>@Html.DisplayFor(modelItem => item.User.Email)</p>*@

                </div>
                <div class="col-sm-3">
                    <h3>$ @Html.DisplayFor(modelItem => item.Price)</h3>
                    <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                </div>
            </div>
        }
    </div>
</div>

@{
    var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
    var nextDisabled = !Model.HasNextPage ? "disabled" : "";
}

<div class="text-center">
    <a asp-controller="Products" asp-action="Index" asp-route-category=@ViewData["CurrentCategory"] asp-route-searchString="@ViewData["CurrentFilter"]" asp-route-userid="@ViewData["CurrentUserId"]" asp-route-pageNumber="@(Model.PageIndex - 1)" class="btn btn-default @prevDisabled">
        Previous
    </a>
    <a asp-controller="Products" asp-action="Index" asp-route-category=@ViewData["CurrentCategory"] asp-route-searchString="@ViewData["CurrentFilter"]" asp-route-userid="@ViewData["CurrentUserId"]" asp-route-pageNumber="@(Model.PageIndex + 1)" class="btn btn-default @nextDisabled">
        Next
    </a>
</div>


@section Scripts {
    <script>
        $('.list-group').on('click', '> a', function (e) {
            var $this = $(this);
            $('.list-group').find('.active').removeClass('active');
            $this.addClass('active');
        });
    </script>
}





@*<table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Title)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Description)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Price)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Image1)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Image2)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Image3)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Status)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.PostedTs)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Category)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.User)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
    @foreach (var item in Model) {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Title)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Price)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Image1)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Image2)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Image3)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Status)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PostedTs)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Category)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.User.Id)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
    }
        </tbody>
    </table>*@