KijijitoForever/KijijitoForever/Controllers/ChatRoomController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using KijijitoForever.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace KijijitoForever.Views.ChatRoom
{
    public class ChatRoomController : Controller
    {
        private readonly kijijito_identityContext _context;
        public readonly UserManager<AppUser> _userManager;
        private readonly UserService _userService;

        public ChatRoomController(kijijito_identityContext context, UserManager<AppUser> userManager)
        {
            _context = context;
            _userManager = userManager;
            _userService = new UserService(_context);
        }

        [Authorize]
        public async Task<IActionResult> Index(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var receiverUser = await _context.AspNetUsers
                .FirstOrDefaultAsync(m => m.Id == id);
            if (receiverUser == null)
            {
                return NotFound();
            }
            ViewBag.ReceiverId = id;
            ViewBag.UserReceiver = receiverUser;
            var currUserName = User.Identity.Name;
            var currUserId = await _userService.GetCurrentUserId(User.Identity.Name);
            ViewBag.CurrentUserName = currUserName;
            ViewBag.CurrentId = currUserId;

            var messagesQuery = _context.Conversations.Where(p => p.SenderId == currUserId || p.ReceiverId == currUserId).Where(p => p.SenderId == id || p.ReceiverId == id).OrderBy(p => p.CreationTs).Include(p => p.Sender).Include(p => p.Receiver).ToList();

            ConversationVM myModel = new ConversationVM();
            //myModel.Messages = _context.Conversations.OrderBy(p => p.CreationTs).Include(p => p.Sender).Include(p => p.Receiver).ToList(); // FIX ME: Filter by users
            myModel.Messages = messagesQuery;
            myModel.NewMessage = new Conversations();
            return View(myModel);
        }

        [HttpPost]
        //[ValidateAntiForgeryToken]
        public void Create(MessageForm conversation)
        {
            //Console.WriteLine("Trying to add a new conversation to database");
            Conversations conversationToSave = new Conversations();
            conversationToSave.SenderId = conversation.SenderId;
            conversationToSave.ReceiverId = conversation.ReceiverId;
            conversationToSave.Message = conversation.Message;
            conversationToSave.Status = ConversationStatusEnum.Sent;
            _context.Add(conversationToSave);
            _context.SaveChanges();
        }
    }
}

KijijitoForever/KijijitoForever/Views/ChatRoom/Index.cshtml
@model KijijitoForever.Models.ConversationVM

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
    //var userName = User.Identity.Name;
    var userReceiver = ViewBag.UserReceiver;
    var userName = ViewBag.CurrentUserName;
    var senderId = ViewBag.CurrentId;
    var receiverId = ViewBag.ReceiverId;
}

<h5>Welcome @userName! Start a conversation with @userReceiver.UserName</h5>


<div class="container">
    <div class="col-md-12">
        <form asp-controller="ChatRoom" asp-action="Create" method="post">
            @*<div asp-validation-summary="ModelOnly" class="text-danger"></div>*@
            <div class="form-group">
                <input asp-for="NewMessage.SenderId" class="form-control" value="@senderId" id="senderIdInput" hidden />
            </div>
            <div class="form-group">
                <input asp-for="NewMessage.ReceiverId" class="form-control" value="@receiverId" id="receiverIdInput" hidden />
            </div>
            <div class="form-group">
                <label asp-for="NewMessage.Message" class="control-label"></label>
                <input asp-for="NewMessage.Message" class="form-control" name="Text" id="messageInput" />
                <span asp-validation-for="NewMessage.Message" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input asp-for="NewMessage.Status" class="form-control" hidden value="Sent" />
            </div>
            <div class="form-group">
                <input type="text" value="@userName" name="username" id="userInput" hidden />
            </div>
            <div class="form-group">
                <input type="submit" value="Send Message" id="sendButton" class="btn btn-outline-primary btn-block" />
            </div>
        </form>
    </div>
</div>

<div class="col-12">
    <hr />
</div>

<div class="row">
    <div class="col-md-12" id="chat">
        @if (Model.Messages != null)
        {
            @foreach (var message in Model.Messages)
            {
                string containerClass, timePosition, textAlign, contcolor, offset;
                if (userName == message.Sender.UserName)
                {
                    containerClass = "container darker";
                    timePosition = "time-right text-light";
                    textAlign = "text-right text-white";
                    contcolor = "bg-primary";
                    offset = "col-md-6 offset-md-6";
                }
                else
                {
                    containerClass = "container";
                    timePosition = "time-left";
                    textAlign = "text-left";
                    contcolor = "bg-light";
                    offset = "col-md-6";
                }

                <div class="row">
                    <div class="@offset">
                        <div class="@containerClass @contcolor">
                            <p class="sender @textAlign">@message.Sender.UserName</p>
                            <p class="@textAlign">@message.Message</p>
                            <span class="@timePosition">@message.CreationTs.ToString("M/dd/yyyy hh:MM tt")</span>
                        </div>
                    </div>
                </div>
            }
        }
    </div>
</div>

<script src="~/js/signalr/dist/browser/signalr.js"></script>
<script type="text/javascript">

    // Start the connection.
    var connection = new signalR.HubConnectionBuilder().withUrl("/chatHub").build();
    //Disable send button until connection is established
    document.getElementById("sendButton").disabled = true;
    // Create a function that the hub can call to broadcast messages
    connection.on("ReceiveMessage", function (user, message) {
        var msg = message.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
        if (msg == "") {
            return;
        }
        var currentdate = new Date();
        var date =
            (currentdate.getMonth() + 1) + "-"
            + currentdate.getDate() + "-"
            + currentdate.getFullYear() + " "
            + currentdate.toLocaleString('en-US', { hour: 'numeric', minute: 'numeric', hour12: true })

        var currUsername = '@(ViewBag.CurrentUserName)';
        //Add message to the page
        addMessageToChat(user, date, msg, currUsername);
    });
    // Transport fallback functionality is now built into start.
    connection.start().then(function () {
        console.log('connection started');
        document.getElementById("sendButton").disabled = false;
    }).catch(function (err) {
        return console.error(err.toString());
    });
    document.getElementById("sendButton").addEventListener("click", function (event) {
        var user = document.getElementById("userInput").value;
        var message = document.getElementById("messageInput").value;
        // Call the Send method on the hub.
        connection.invoke("SendMessage", user, message).catch(function (err) {
            return console.error(err.toString());
        });
        // Clear text box and reset focus for next comment.
        addMessageToDatabase();
        messageInput.value = '';
        event.preventDefault();
    });



    function addMessageToChat(user, date, msg, currUsername) {
        let isCurrentUserMessage = false;
        if (user === currUsername) {
            isCurrentUserMessage = true;
        }
        let container = document.createElement('div');
        container.className = isCurrentUserMessage ? "col-md-6 offset-md-6 container darker bg-primary" : "container text-left bg-light";
        let sender = document.createElement('p');
        sender.className = isCurrentUserMessage ? "text-right text-white" : "text-left";
        sender.innerHTML = user;
        let text = document.createElement('p');
        text.className = isCurrentUserMessage ? "text-right text-white" : "text-left";
        text.innerHTML = msg;
        let when = document.createElement('span');
        when.className = isCurrentUserMessage ? "time-right text-light" : "text-left";
        when.innerHTML = date;
        container.appendChild(sender);
        container.appendChild(text);
        container.appendChild(when);
        chat.appendChild(container);
    }

    function addMessageToDatabase() {
        var messageForm = {
            SenderId: document.getElementById("senderIdInput").value,
            ReceiverId: document.getElementById("receiverIdInput").value,
            Message: document.getElementById("messageInput").value,
            Status: "Sent"
        }
        var dataStr = JSON.stringify(messageForm);
        $.ajax({
            //url: 'https://localhost:44348/ChatRoom/Create',
            url: 'https://kijijito.azurewebsites.net/ChatRoom/Create',
            type: 'POST',
            dataType: "html",
            data: messageForm,
            error: function (jqxhr, status, errorThrown) {
                //alert("AJAX error: " + jqxhr.responseText + status);
                alert("Ops! Your message was not saved");
            }
        });
    }

</script>